# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BenhVien-app' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 1.0'
pod 'PureLayout', '~> 3.0'
pod 'IQKeyboardManager', '~> 4.0'
pod 'IQDropDownTextField', '~> 1.1'
pod 'KASlideShow', '~> 3.0'
pod 'SDWebImage', '~> 3.8.2'
end
